name: POSCLIENT-FRONT CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/posclient-front/**'
      - '.github/workflows/ci-apps-posclient-front.yml'
  pull_request:
    paths:
      - 'apps/posclient-front/**'
      - '.github/workflows/ci-apps-posclient-front.yml'

jobs: 
  pos-ui:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Build
        run: |
          cd pos
          rm -rf node_modules
          npm install
          npm run build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main')
        run: |
          cd pos
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          DOCKER_BUILDKIT=1 docker build -t erxes/pos-ui:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/pos-ui:${GITHUB_REF#refs/heads/}
