name: CI plugin-operation_ui

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/plugins/operation_ui/**'
      - 'frontend/libs/**'
      - '.github/workflows/ci-ui-operation.yml'
  pull_request:
    paths:
      - 'frontend/plugins/operation_ui/**'
      - 'frontend/libs/**'
      - '.github/workflows/ci-ui-operation.yml'

permissions:
  actions: read
  contents: read
  packages: write
  id-token: write

jobs:
  operation_ui-ci:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build operation UI
        run: |
          export NX_DAEMON=false
          pnpm nx build operation_ui

      - name: Sync to Cloudflare R2
        run: |
          aws s3 sync dist/frontend/plugins/operation_ui s3://erxes-next/latest/operation_ui/ \
            --endpoint-url https://7c8392aff8ac4518aa06dfa4b6337ef2.r2.cloudflarestorage.com
