name: UI CI

on:
  push:
    branches:
      - federation
    paths:
      - 'packages/erxes-ui/**'
      - 'packages/core-ui/**'
      - '.github/workflows/coreui.yaml'
      - '!ui/nginx/**'
      - '!ui/docker-entrypoint.sh'
      - '!ui/Dockerfile'
      - '!ui/.dockerignore'

jobs:
  ui:
    runs-on: ubuntu-18.04

    steps:
      - name: Use Node.js 14.20.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.x

      - uses: actions/checkout@v2

      - name: Build
        run: |
          ls -la
          ls -ls packages
          cd packages/core-ui
          yarn install --frozen-lockfile
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/federation')
        env:
          BASE_IMAGE: erxes/erxes:base-1.18-alpine
        run: |
          cd packages/core-ui
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          DOCKER_BUILDKIT=1 docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t erxes/erxes:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/erxes:${GITHUB_REF#refs/heads/}