name: UI CI

on:
  push:
    branches:
      - dev
      - staging
      - build-test
    paths:
      - 'packages/erxes-ui/**'
      - 'packages/core-ui/**'
      - '.github/workflows/coreui.yaml'
      - '!ui/nginx/**'
      - '!ui/docker-entrypoint.sh'
      - '!ui/Dockerfile'
      - '!ui/.dockerignore'

jobs:
  ui:
    runs-on: ubuntu-22.04

    steps:
      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x

      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd packages/core-ui
          yarn install --frozen-lockfile
          yarn build

      - name: Configure AWS credentials
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test' )
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy locales
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test' )
        run: |
          tar -cf locales.tar --directory=packages/core-ui/public/locales .
          aws s3 cp locales.tar s3://erxes-${GITHUB_REF#refs/heads/}-plugins/locales.tar

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test' )
        env:
          BASE_IMAGE: erxes/erxes:base-1.18-alpine
        run: |
          cd packages/core-ui
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          DOCKER_BUILDKIT=1 docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t erxes/erxes:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/erxes:${GITHUB_REF#refs/heads/}
