name: Engages CI

on:
  push:
    branches:
      - "**"
    paths:
      - "engages-email-sender/**"
      - ".github/workflows/engages.yaml"
  pull_request:
    branches:
      - priuscenter
    paths:
      - "engages-email-sender/**"
      - ".github/workflows/engages.yaml"

jobs:
  engages:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.20.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.20.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-engages-email-sender-${{ hashFiles('yarn.lock', 'engages-email-sender/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-engages-email-sender-
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install
          cd engages-email-sender
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint engages-email-sender

      - name: Build
        run: |
          cd engages-email-sender
          rm -rf node_modules
          yarn install --frozen-lockfile --production
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/priuscenter' )
        run: |
          cd engages-email-sender
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build -t ${{ secrets.REGISTRY_URL }}/erxes-enterprise/erxes-engages-email-sender:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push ${{ secrets.REGISTRY_URL }}/erxes-enterprise/erxes-engages-email-sender:${GITHUB_REF#refs/heads/}
