name: Essyncer CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'essyncer/**'
      - '.github/workflows/essyncer.yaml'

  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'essyncer/**'
      - '.github/workflows/essyncer.yaml'

jobs:
  essyncer:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' )
      run: |
        cd essyncer
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t erxes/erxes-essyncer:${GITHUB_REF#refs/heads/} -f Dockerfile .
        docker push erxes/erxes-essyncer:${GITHUB_REF#refs/heads/}
