name: Logger CI

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'logger/**'
      - '.github/workflows/logger.yaml'
    tags:
      - '*'

jobs:
  logger:
    runs-on: ubuntu-18.04

    # name: Node ${{ matrix.node-version }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # https://github.com/actions/cache/blob/master/examples.md#node---yarn
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache Node.js modules
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-logger-${{ hashFiles('logger/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-logger-${{ hashFiles('logger/**/yarn.lock') }}
          ${{ runner.os }}-yarn-logger-
          ${{ runner.os }}-yarn-

    - name: Install
      run: |
        cd logger
        yarn install

    - name: Build
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' )
      run: |
        cd logger
        yarn build

    - name: Build docker image [push]
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' )
      run: |
        cd logger
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t erxes/erxes-logger:${GITHUB_REF#refs/heads/} -f Dockerfile .
        docker push erxes/erxes-logger:${GITHUB_REF#refs/heads/}

    - name: Build docker image [tag]
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      run: |
        cd logger
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker build -t erxes/erxes-logger:${GITHUB_REF#refs/tags/} -f Dockerfile .
        docker push erxes/erxes-logger:${GITHUB_REF#refs/tags/}
