name: Plugin emailtemplates Api CI

on:
  push:
    branches:
      - federation
    paths:
      - 'packages/api-utils/**'
      - 'packages/api-plugin-template.erxes/**'
      - 'packages/plugin-emailtemplates-api/**'
      - '.github/workflows/plugin-emailtemplates-api.yaml'

jobs:
  api:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.20.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.20.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-plugin-emailtemplates-api-${{ hashFiles('yarn.lock', 'plugin-emailtemplates-api/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-plugin-emailtemplates-api-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cd packages/gateway
          yarn install
          yarn build plugin emailtemplates
          cd ../../dist/plugin-emailtemplates-api/.erxes
          cd dist/main/.erxes/src1

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/federation'  )
        run: |
          ls -la dist
          ls -la dist/plugin-emailtemplates-api
          cd dist/plugin-emailtemplates-api/.erxes
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/plugin-emailtemplates-api:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/plugin-emailtemplates-api:${GITHUB_REF#refs/heads/}