name: Plugin UI CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'packages/plugin-logs-ui/**'
      - '.github/workflows/plugin-logs-ui.yaml'

jobs:
  ui:
    runs-on: ubuntu-18.04

    steps:
      - name: Use Node.js 14.18.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.x

      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install --frozen-lockfile
          # cp -r packages/ui-plugin-template/.erxes packages/plugin-logs-ui/.erxes
          cd packages/plugin-logs-ui
          yarn install-deps
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy
        run: |
          aws s3 sync packages/plugin-logs-ui/.erxes/dist s3://plugin-uis/plugin-logs-ui --delete 