name: Plugin {sample} Api CI

on:
  push:
    branches:
      - dev
      - staging
      - build-test
    paths:
      - 'packages/api-utils/**'
      - 'packages/api-plugin-template.erxes/**'
      - 'packages/plugin-{sample}-api/**'
      - '.github/workflows/plugin-{sample}-api.yaml'
  pull_request:
    branches:
      - dev
      - staging
      - build-test
    paths:
      - 'packages/api-utils/**'
      - 'packages/api-plugin-template.erxes/**'
      - 'packages/plugin-{sample}-api/**'
      - '.github/workflows/plugin-{sample}-api.yaml'

jobs:
  api:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-plugin-{sample}-api-${{ hashFiles('yarn.lock', 'plugin-{sample}-api/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-plugin-{sample}-api-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cp -r builder dist
          cd dist
          yarn install
          yarn build plugin {sample}
          cd plugin-{sample}-api/.erxes
          cd dist/main/.erxes/src

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test' )
        run: |
          cd dist/plugin-{sample}-api/.erxes
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/plugin-{sample}-api:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/plugin-{sample}-api:${GITHUB_REF#refs/heads/}
