name: Widgets CI

on:
  push:
    branches:
      - 'dev'
    paths:
      - "widgets/**"
      - ".github/workflows/widgets.yaml"
  pull_request:
    branches:
      - master
      - dev
    paths:
      - "widgets/**"

jobs:
  widgets:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.20.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-widgets-${{ hashFiles('yarn.lock', 'widgets/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-widgets-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cd widgets
          rm -rf node_modules
          yarn install --frozen-lockfile --production
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' )
        run: |
          cd widgets
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/erxes-widgets:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/erxes-widgets:${GITHUB_REF#refs/heads/}