name: Workers CI

on:
  push:
    branches:
      - 'dev'
      - master
      - rc
      - 'staging'
    paths:
      - 'packages/api-utils/**'
      - 'packages/workers/**'
      - '.github/workflows/workers.yaml'

jobs:
  workers:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-api-workers
          restore-keys: |
            ${{ runner.os }}-yarn-api-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cp -r builder dist
          cd dist
          yarn install
          yarn build workers

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' )
        run: |
          cd dist/erxes
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker buildx build -t erxes/workers:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/workers:${GITHUB_REF#refs/heads/}
