name: Workers CI

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'packages/api-utils/**'
      - 'packages/api-plugin-template.erxes/**'
      - 'packages/workers/**'
      - '.github/workflows/workers.yaml'

jobs:
  workers:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.20.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-workers-${{ hashFiles('yarn.lock', 'workers/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-workers
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cp -r builder dist
          cd dist
          yarn install
          yarn build workers

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'  )
        run: |
          cd dist/workers
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/workers:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/workers:${GITHUB_REF#refs/heads/}